### PR TITLE
Fix delegation on Ruby 2.7

### LINKED ISSUE #44: Warning related to key word argument
Hi @ms-ati ,

Following warning related to key word argument is displayed when an method including key word argument is called withing DSL block.

```
/opt/rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/docile-1.3.2/lib/docile/fallback_context_proxy.rb:87: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
```

Execute this example code  then you will see the above warning.

```ruby
class Foo
  def bar(baz: 0)
  end
end

require 'docile'
Docile.dsl_eval(Foo.new) do
  bar(baz: 1)
end
```

* Ruby version: ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux]
* Docile version: 1.3.2

### LINKED ISSUE #396: truffleruby-head build is failing
The truffleruby build is failing for some reason. For example https://github.com/jwt/ruby-jwt/runs/1591113294

Is there something we could do? @gogainda @eregon

### PR DESCRIPTION
**Pull request by eregon**
* `(*args, **kwargs)`-delegation does not work on Ruby 2.7.

See https://eregon.me/blog/2019/11/10/the-delegation-challenge-of-ruby27.html#ruby-3-style-delegation
and https://www.ruby-lang.org/en/news/2019/12/12/separation-of-positional-and-keyword-arguments-in-ruby-3-0/#a-compatible-delegation for more details.

Addresses https://github.com/ms-ati/docile/pull/45#discussion_r547216011
and properly fixes https://github.com/ms-ati/docile/issues/44.

Also fixes https://github.com/jwt/ruby-jwt/issues/396 and in general many SimpleCov usages.

@taichi-ishitani I wonder, was https://www.ruby-lang.org/en/news/2019/12/12/separation-of-positional-and-keyword-arguments-in-ruby-3-0/ confusing? It intends to say "use ruby2_keywords; `(*args, **kwargs)`-delegation does not work on Ruby 2.7". But maybe it needs to be clarified further?

### CODE REVIEW

**Comment by taichi-ishitani** [comment]
@eregon ,
Thank you for fixing a bug caused by my PR.
I misread the article.

**Comment by eregon** [comment]
@taichi-ishitani No worry. Do you have any suggestion how to improve the article to be clearer? It seems at least a few people got confused by it.

**Comment by ms-ati** [comment]
Thank you for this fix @eregon ! I will make a release that includes this

**Comment by eregon** [comment]
Thanks!

**Comment by ms-ati** [comment]
@eregon I've just released v1.3.4 to rubygems, which includes this PR. Thanks again.

**Pull request merged**
